# 本文件将基于kbox基础云手机镜像和kbox二进制制作适用于amd gpu 云手机镜像
# 本文件前提是保证已有kbox基础云手机镜像（如kbox:latest）
# 在kbox基础云手机镜像的基础上将kbox二进制放入kbox基础云手机镜像中
# 使用docker命令制作kbox云手机镜像，方便用户使用

# ARG是定义参数名称
# FROM是指定kbox基础云手机镜像
# MAINTAINER是作者名
ARG KBOX_IMAGE
FROM ${KBOX_IMAGE}
MAINTAINER root

COPY ./imageFile/system /imageFile/system

# 注意：
# 因为每运行RUN一次就会创建一层镜像，容易产生非常臃肿、非常多层的镜像
# 所以将视频流云手机相关的所有二进制整合在一起，保证只运行一次RUN
RUN chmod -R 755 imageFile \
    && chown -R root:root imageFile \
    && cp -pR imageFile/system/* /system/ \
    && rm -rf imageFile
