# ******************************************************************************** #
# Copyright Kbox Technologies Co., Ltd. 2020-2022. All rights reserved.
# File Name: build.conf
# Description: Android编译环境配置
# ******************************************************************************** #


KBOX_AOSP_PATH="/home/auto_compile"

AOSP_PATH="$KBOX_AOSP_PATH/aosp"

PACKAGE_PATH="$KBOX_AOSP_PATH/package"

DNS=114.114.114.114

buildtools_path="$KBOX_AOSP_PATH/buildtools"

meson_version="1.1.0"
meson_dir="meson-${meson_version}"

mesa_version="24.3.4"
mesa_src="mesa-24.3.4"

vmi_cloudphone_src="vmi-CloudPhone"

PATCH_PATH="$KBOX_AOSP_PATH/patchForAndroid"
